name: libsignal_protocol_dart
description: Signal Protocol libray for Dart native and Flutter, pure Dart implementation of the the Signal Protocol
version: 0.7.0
repository: https://github.com/MixinNetwork/libsignal_protocol_dart
topics:
 - crypto

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  adaptive_number: ^1.0.0
  collection: ^1.17.2
  convert: ^3.1.1
  crypto: ^3.0.3
  ed25519_edwards: ^0.3.1
  fixnum: ^1.0.0
  meta: ^1.7.0
  optional: ^6.1.0+1
  pointycastle: ^3.7.3
  protobuf: ^2.0.0
  very_good_analysis: ^5.0.0+1
  x25519: ^0.1.1


dev_dependencies:
  test: ^1.24.3
