name: libsignal_protocol_dart
description: Signal Protocol libray for Dart native and Flutter, pure Dart implementation of the the Signal Protocol
version: 0.3.0-nullsafety.0
homepage: https://github.com/MixinNetwork/libsignal_protocol_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.1
  optional: ^6.0.0-nullsafety.0
  tuple: ^2.0.0
  fixnum: ^1.0.0
  collection: ^1.15.0
  // upgrade to pre-release of pointycastle to enable full websupport
  pointycastle: ^3.2.0-rc0
  ed25519_edwards: ^0.1.0
  x25519: ^0.0.2


dev_dependencies:
  test: ^1.16.5 
  pedantic: ^1.11.0
