name: libsignal_protocol_dart
description: Signal Protocol libray for Dart native and Flutter, pure Dart implementation of the the Signal Protocol
version: 0.5.4
homepage: https://github.com/MixinNetwork/libsignal_protocol_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.1
  ed25519_edwards: ^0.3.1
  fixnum: ^1.0.0
  meta: ^1.7.0
  optional: ^6.1.0+1
  pointycastle: ^3.3.4
  protobuf: ^2.0.0
  tuple: ^2.0.0
  very_good_analysis: ^2.3.0
  # upgrade to pre-release of pointycastle to enable full websupport
  x25519: ^0.1.1


dev_dependencies:
  test: ^1.17.12
