name: libsignal_protocol_dart
description: Signal Protocol libray for Dart native and Flutter, pure Dart implementation of the the Signal Protocol
version: 0.2.1
homepage: https://github.com/MixinNetwork/libsignal_protocol_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  protobuf: ^1.1.1
  convert: ^2.1.1
  crypto: ^2.1.5
  optional: ^5.0.0+1
  tuple: ^1.0.3
  fixnum: ^0.10.11
  collection: ^1.14.13
  pointycastle: ^2.0.1
  ed25519_edwards: ^0.0.5
  curve25519:
    git:
      url: git@github.com:Tougee/curve25519.git
      ref: main

dev_dependencies:
  test: ^1.15.1
  pedantic: ^1.9.2
